version: '3.6'

services:

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: sh -c "celery -A periodic worker -l info"
    volumes:
      - .:/code
    depends_on:
      - redis

  celery-beat:
    build: .
    command: sh -c "celery -A periodic beat -l info"
    volumes:
      - .:/code
    depends_on:
      - redis
